# Site settings
title: Shane Khalid
description: 'Machine Learning Researcher and Web Developer'
url: 'https://prettypositron.github.io/'
baseurl: '/minimal'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Adnan Khalid'
  email: adnan@adnankhalid.com
 

  github_username:  prettypositron
  linkedin_username:  akhalid16

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
